name: Deploy Website

on:
  push:
    branches:
      - aws/main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_S3_REGION }}
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install modules
        run: pnpm install
      - name: Build application
        run: pnpm build
      - name: Deploy to S3
        run: aws s3 sync ./out/ s3://${{ vars.AWS_S3_BUCKET_NAME }}
      - name: Create CloudFront invalidation
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CF_DISTRIBUTION_ID }} --paths "/*"
